sudo: required
dist: trusty
language: javascript
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - graphicsmagick
before_install:
  - nvm install 8
  - nvm use 8
  - npm install -g npm typings
  - npm -v
  - node -v
install:
  - npm install

jobs:
  include:
    #TESTS
    - stage: Test
      script:
        - ./node_modules/.bin/ng lint || true
        - ./node_modules/.bin/ng test --single-run --code-coverage || true
        - ng build --prod #Make sure build is working
    #DEPLOY
    - stage: Deploy
      script:
        - ./node_modules/.bin/ng build --prod
      deploy:
        #Deploy development version
        - provider: s3
          access_key_id: $AWS_KEY
          secret_access_key: $AWS_SECRET
          bucket: $AWS_BUCKET
          skip_cleanup: true
          upload-dir: "dev"
          local_dir: "dist"
          region: eu-central-1
          acl: public_read
          on:
            branch: master
        #Deploy PRODUCTION VERSION
        - provider: s3
          access_key_id: $AWS_KEY
          secret_access_key: $AWS_SECRET
          bucket: $AWS_BUCKET
          skip_cleanup: true
          upload-dir: "prod"
          local_dir: "dist"
          region: eu-central-1
          acl: public_read
          on:
            tags: true
